---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: macosx
    driver:
      box: roboticcheese/macosx
      ssh:
        insert_key: false
      gui: true

suites:
  - name: default
    run_list:
      - recipe[divvy]
    attributes:
      mac_app_store:
        username: <%= ENV['APPLE_ID_USERNAME'] %>
        password: <%= ENV['APPLE_ID_PASSWORD'] %>
